[2022-11-29T12:18:29.734+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T12:12:26.841273+00:00 [queued]>
[2022-11-29T12:18:29.742+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T12:12:26.841273+00:00 [queued]>
[2022-11-29T12:18:29.742+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T12:18:29.742+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T12:18:29.742+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T12:18:29.757+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 12:12:26.841273+00:00
[2022-11-29T12:18:29.760+0000] {standard_task_runner.py:55} INFO - Started process 232 to run task
[2022-11-29T12:18:29.762+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T12:12:26.841273+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmphsid5pw4']
[2022-11-29T12:18:29.763+0000] {standard_task_runner.py:83} INFO - Job 74: Subtask extract
[2022-11-29T12:18:29.808+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T12:12:26.841273+00:00 [running]> on host 20e1b9fbda6e
[2022-11-29T12:18:29.855+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T12:12:26.841273+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T12:12:26.841273+00:00
[2022-11-29T12:18:29.856+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T12:18:29.856+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/python_scripts/extract.py']
[2022-11-29T12:18:29.862+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T12:18:29.951+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/python_scripts/extract.py': [Errno 2] No such file or directory
[2022-11-29T12:18:29.954+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T12:18:29.961+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T12:18:29.964+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T121226, start_date=20221129T121829, end_date=20221129T121829
[2022-11-29T12:18:29.976+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 74 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 232)
[2022-11-29T12:18:30.014+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T12:18:30.033+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
