[2022-11-29T10:01:56.456+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T09:56:55.865991+00:00 [queued]>
[2022-11-29T10:01:56.465+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T09:56:55.865991+00:00 [queued]>
[2022-11-29T10:01:56.465+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T10:01:56.465+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-29T10:01:56.465+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T10:01:56.483+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 09:56:55.865991+00:00
[2022-11-29T10:01:56.487+0000] {standard_task_runner.py:55} INFO - Started process 211 to run task
[2022-11-29T10:01:56.489+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T09:56:55.865991+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpsz4m0z3g']
[2022-11-29T10:01:56.490+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask extract
[2022-11-29T10:01:56.547+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T09:56:55.865991+00:00 [running]> on host 44d54c669ba0
[2022-11-29T10:01:56.643+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T09:56:55.865991+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T09:56:55.865991+00:00
[2022-11-29T10:01:56.644+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T10:01:56.645+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/dags/extract.py']
[2022-11-29T10:01:56.658+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T10:01:56.802+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/dags/extract.py': [Errno 2] No such file or directory
[2022-11-29T10:01:56.805+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T10:01:56.817+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T10:01:56.821+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl, task_id=extract, execution_date=20221129T095655, start_date=20221129T100156, end_date=20221129T100156
[2022-11-29T10:01:56.839+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 211)
[2022-11-29T10:01:56.862+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T10:01:56.895+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
