[2022-11-29T10:07:58.763+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T10:01:55.865991+00:00 [queued]>
[2022-11-29T10:07:58.773+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T10:01:55.865991+00:00 [queued]>
[2022-11-29T10:07:58.773+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T10:07:58.774+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T10:07:58.774+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T10:07:58.793+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 10:01:55.865991+00:00
[2022-11-29T10:07:58.797+0000] {standard_task_runner.py:55} INFO - Started process 303 to run task
[2022-11-29T10:07:58.798+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T10:01:55.865991+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpo8yrmwe0']
[2022-11-29T10:07:58.799+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask extract
[2022-11-29T10:07:58.856+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T10:01:55.865991+00:00 [running]> on host 8cd23ebf6eb4
[2022-11-29T10:07:58.928+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T10:01:55.865991+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T10:01:55.865991+00:00
[2022-11-29T10:07:58.929+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T10:07:58.930+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/dags/extract.py']
[2022-11-29T10:07:58.937+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T10:07:59.025+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/dags/extract.py': [Errno 2] No such file or directory
[2022-11-29T10:07:59.028+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T10:07:59.037+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T10:07:59.040+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T100155, start_date=20221129T100758, end_date=20221129T100759
[2022-11-29T10:07:59.054+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 303)
[2022-11-29T10:07:59.091+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T10:07:59.116+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
